import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner";
import "../../globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/AppSidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <SidebarProvider className="flex ">
        <AppSidebar />
        <main className="flex-1 overflow-auto bg-slate-50">
          {/* <SidebarTrigger /> */}
          {children}
        </main>
      </SidebarProvider>
      <Toaster position="top-right" />
    </div>
  );
}
